Завершение верстки
htmlacademy-htmlcss/1652933-sedona-31 pull request #13
Opened 2021-06-27 05:38 UTC by ekimey9050

2021-06-27 19:11 UTC, Pakistanka requested changes
1. Потерян атрибут href - http://joxi.ru/KAxkQ70svwRNY2. При нажатии на логотип я должна переходить на главную страницу, а этого сейчас не происходит
2. Переименую Normalize.css на normalize.css - мы не используем прописную букву в названии файлов
3. Все дробный значения нужно округлить

2021-06-27 19:11 UTC, Pakistanka commented on catalog.html
> +    <link rel="stylesheet" href="css/Normalize.css">
Переименнуй файл Normalize.css на normalize.css

2021-06-27 19:11 UTC, Pakistanka commented on css/style.css
> +    width: 33.3%;
Мы не используем дробные значение. Округляй

2021-06-28 15:34 UTC, ekimey9050 commented
Внесены изменения, согласно замечаниям

2021-06-28 16:12 UTC, merged