Разметка главной страницы и каталога
htmlacademy-htmlcss/1652933-sedona-31 pull request #2
Opened 2021-05-22 14:29 UTC by ekimey9050

2021-05-23 11:52 UTC, Pakistanka requested changes
1. Поправить ошибки, которые показал валидатор
2. Поправить наименования изображения, убрать px, добавить alt атрибуты
3. Поправить форматирование файла.

2021-05-23 11:52 UTC, Pakistanka commented on catalog.html
> +    <title>Каталог</title>
Нарушена стилистика форматирования. Код должен быть лесенкой

2021-05-23 11:52 UTC, Pakistanka commented on catalog.html
> +                <img src="image/Layer 21.png" width="135" height="90">
В наименовании картинок не должно быть пробелов, нечитаемых пробел, русских букв.

Эта картинка не загрузится на странице.
Также, лучше давать картинкам логически понятные названия. Данное название будет вызывать у тебя каждый раз вопрос "Что же это за картинка?"

Также был потерян alt атрибут, а он обязательно должен быть и заполненные

2021-05-23 11:52 UTC, Pakistanka commented on catalog.html
> +                <img src="image/Layer 89 copy.png" width="135" height="90">
В наименовании картинок не должно быть пробелов, нечитаемых пробел, русских букв.

Эта картинка не загрузится на странице.
Также, лучше давать картинкам логически понятные названия. Данное название будет вызывать у тебя каждый раз вопрос "Что же это за картинка?"

Также был потерян alt атрибут, а он обязательно должен быть и заполненные

2021-05-23 11:52 UTC, Pakistanka commented on catalog.html
> +                <img src="image/Rectangle.png" width="135" height="90">
Имя картинки непонятное и нет alt атрибута

2021-05-23 11:52 UTC, Pakistanka commented on catalog.html
> +<!DOCTYPE html>
Есть ошибки в разметке - https://prnt.sc/13awj5d
Проверь код через валидатор

2021-05-23 11:52 UTC, Pakistanka commented on index.html
>  <html lang="ru">
Также множество ошибок по валидатору

2021-05-23 11:52 UTC, Pakistanka commented on index.html
> +        <img src="image/background photo.png" alt="Sedona" width="1200px" height="453px"> <!--SVG???-->
В свойствах width и height, если они пишутся в разметке не должно быть указания единиц измерения, так как они не сработают

Также в наименовании картинок не должно быть пробелов, нечитаемых пробел, русских букв.

2021-05-24 14:08 UTC, ekimey9050 commented
Внесены изменения

2021-05-24 15:02 UTC, merged