Сетка основных блоков главной страницы
htmlacademy-htmlcss/1652933-sedona-31 pull request #7
Opened 2021-06-05 15:19 UTC by ekimey9050

2021-06-06 18:41 UTC, Pakistanka requested changes

2021-06-06 18:41 UTC, Pakistanka commented on catalog.html
>            <a class="main-header-logo"><img src="image/logo.svg" alt="Логотип сайта Седона"></a>
Перенеси картинку на следующую строку и поправь форматирование, так будет правильнее

2021-06-06 18:41 UTC, Pakistanka commented on catalog.html
> +                <div class="Group-1">
имена классов должны быть написаны с маленькой буквы.

Также имя класса должно носить осмысленное название, отвечающее на вопрос "О чем этот блок?"
О чем group-1 я не понимаю. Нужно заменить и поправить по всему сайту

2021-06-06 18:41 UTC, Pakistanka commented on catalog.html
>                  <fieldset class="Group">
Что за Group? Почему с большой буквы?

2021-06-06 18:41 UTC, Pakistanka commented on catalog.html
> +                <div class="filter-checkbox-2">
Зачем делаешь лишние обертки?
У тебя есть fieldset, который является оберткой всему блоку.

2021-06-06 18:41 UTC, Pakistanka commented on catalog.html
> +                    <a href="#" class="side-item-plus"> <svg width="11" height="10" viewBox="0 0 11 10" xmlns="http://www.w3.org/2000/svg">
Нарушено форматирование

2021-06-06 18:41 UTC, Pakistanka commented on style.css
> +    margin-bottom: 16,5px;
Нужно определиться какой ты используешь разделитель, так как у  margin-top и margin-bottom используется в одном случае точка, в другом запятая.

Плюс, использование дробных выражений - плохая практика.

2021-06-06 18:41 UTC, Pakistanka commented on style.css
>  .content h3 {
Мы не вешаем стили на теги. Лучше повесить на h3 класс и по нему вызывать

2021-06-06 18:41 UTC, Pakistanka commented on style.css
> +    /*внешние отступы не работают*/
А какие внешние отступы ты здесь хочешь добавить? (верхние/нижние) 
У тебя сейчас блок стоит ровно по центру, так как у родителя прописано центрирование гридами

2021-06-07 13:49 UTC, ekimey9050 commented
Внесла изменения согласно комментариям, прошу проверить

2021-06-08 08:09 UTC, merged