Флексы главной странице
htmlacademy-htmlcss/1652933-sedona-31 pull request #9
Opened 2021-06-12 14:41 UTC by ekimey9050

2021-06-13 09:20 UTC, Pakistanka requested changes

2021-06-13 09:20 UTC, Pakistanka commented on index.html
> +        <a class="main-header-logo"><img class="main-header-logo" src="image/logo.svg" alt="Логотип сайта Седона"></a>
У картинки и ссылки одинаковые классы. Это - ошибка. Одинаковые классы могут быть только одинаковые элементы, а ссылка несет роль обертки, а картинка картинки. 

Нужно поменять классы

2021-06-13 09:20 UTC, Pakistanka commented on index.html
> +          <li class="photo"><a href="blank.html">Фото и видео</a></li>
А почему остальным элементам не стала добавлять классы?

2021-06-13 09:20 UTC, Pakistanka commented on style.css
>  .demography {
Выравнивание внутри input поломано - http://joxi.ru/Dr8YwOzTJJMzNm

2021-06-13 09:20 UTC, Pakistanka commented on index.html
>                <input class="data" type="text" id="datearrival" value="24 апреля 2017">
Для placeholder нужен отступ, чтобы контент не прилипал - http://joxi.ru/E2pZJ97t44GGjr

2021-06-13 09:20 UTC, Pakistanka commented on style.css
> +.photo {
Большой margin-right. Нужно что-то другое придумать, чтобы не делать таких больших отступов

2021-06-13 09:20 UTC, Pakistanka commented on style.css
>      padding-top: 69,2px;
Округляй значения. Использовать дробные - плохая практика

2021-06-13 15:40 UTC, ekimey9050 commented
Внесла правки, согласно замечаниям

2021-06-14 19:14 UTC, Pakistanka approved these changes

2021-06-14 19:14 UTC, merged